# Generated by Django 4.2.3 on 2023-07-05 17:40

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('slug', models.CharField(max_length=256, unique=True)),
                ('schema', models.JSONField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now)),
                ('modifield_on', unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now)),
            ],
        ),
    ]
