# Generated by Django 4.2.3 on 2023-07-07 05:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import unixtimestampfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now)),
                ('modifield_on', unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_instant', to='myapp.user')),
            ],
        ),
    ]
